FROM node:16-alpine

WORKDIR /home/api-movies

RUN npm install -g @nestjs/cli

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

ENTRYPOINT [ "npm", "run", "start" ]

USER node

EXPOSE 3333