version: '3.6'

services:
  movies:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: api-movies
    ports:
      - 3300:3300
    restart: always
    volumes:
      - ./:/home/api-movies
    tty: true
    environment: 
      MONGODB: "mongodb://${MONGO_DEV_USER}:${MONGO_DEV_PWD}@${MONGO_DEV_HOST}:27017/julianaoliveira?authMechanism=DEFAULT&replicaSet=rs0&readPreference=secondaryPreferred&authSource=admin" 
    networks:
      - api-movies


networks:
  api-movies:
    driver: bridge
